### ISSUE TITLE
Extensions page blocked

### ISSUE THREAD

**Issue by nbycoder** [Trzynastek/Arctic-Floorp#1]
Hello! Just letting you know that when trying to install an add-on, the pop-up for confirmation doesn't show! 

Also, is there any way to prevent the url bar from collapsing? Thanks :)

**Comment by Trzynastek** [comment]
You can disable the url bar collapsing by editing the userChrome.css file.
By default line 71 should look like this:
```
#navigator-toolbox:is(:hover, :focus-within) #nav-bar:not([customizing]):not(:has(#unified-extensions-button:hover, #unified-extensions-button:focus)) {
```
All you need to do is change it to this:
```
 #navigator-toolbox #nav-bar:not([customizing]) {
```
This should stop the url bar from collapsing.

As for the add-on pop-up, I will look into it when I have some time.
I'm guessing it's caused by some changes in newer versions of the browser.

**Comment by Trzynastek** [comment]
I can't replicate the issue with the add-on pop-up not appearing.
Does this happen for all extensions or only a specific one?
Also, what browser version are you using?

**Comment by nbycoder** [comment]
It happens with all of them! I think it might be a theme issue because when I changed it to something else it worked. And I'm using Floorp 11.20.0 :) Installed through the PPA.

**Comment by Trzynastek** [comment]
I honestly have no clue what is causing this. I tried it on a fresh VM, and I still can't replicate the issue.
You could try removing lines from 203 to 250 since they might be causing some issues.
If that doesn't help I don't think I can do anything further.

**Comment by nbycoder** [comment]
![screenshot-2024-11-06-17-43-11](https://github.com/user-attachments/assets/bd77cae1-0fdb-462d-b394-452f203d7a47)


So I think the issue is actually the positioning of the extension button? Though I don't know why this is suddenly a problem, because when I first started using this theme it worked fine.

**Comment by Trzynastek** [comment]
That's weird. Normally, this window should not be able to appear outside the windows if it would not be visible. 
 I don't think it's possible to move this pop-up with CSS or at least I can't figure out how to do it. 
The only solution would be to move the button back to the url bar.
This can be done by removing lines 345 to 363 and 365 to 377 from the userChrome.css.

**Comment by nbycoder** [comment]
I can confirm that moving the extensions button back fixes this!

**Comment by Trzynastek** [comment]
I'm glad to hear it's working.
Since changing the pop-up location with CSS doesn't seem possible, there is no other solution for now.
I won't be implementing this fix since the issue seems to appear only in very specific scenarios.
